apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: default

spec:
  type: ClusterIP

  selector:
    app: auth-pod
    # must match pod label
    # deployment.yaml > spec.template.metadata.labels.app

  ports:
    - protocol: TCP
      port: 3000
      # publicly accessible port
      # ingress forwards traffic here

      targetPort: 3000
      # container port inside the pod

  sessionAffinity: None
  # Options:
  # ClientIP or None
  # ClientIP keeps requests from same client
  # on the same pod (sticky sessions)